[project]
name = "odoo-addons-oca-purchase-reporting"
version = "17.0.20250604.0"
dependencies = [
    "odoo-addon-purchase_comment_template>=17.0dev,<17.1dev",
    "odoo-addon-purchase_order_report_grouped_by_vendor>=17.0dev,<17.1dev",
    "odoo-addon-purchase_report_hide_line>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
